# Adds `pio run -t select_port`: lists the serial ports and saves the chosen one
# to port.local.ini (not committed), which platformio.ini loads via extra_configs.
Import("env")

import os

from serial.tools import list_ports

LOCAL_INI = os.path.join(env.subst("$PROJECT_DIR"), "port.local.ini")


def select_port(*args, **kwargs):
    ports = sorted(list_ports.comports(), key=lambda p: p.device)
    print()
    for i, port in enumerate(ports, 1):
        print(f"  {i}) {port.device}  {port.description}")
    if not ports:
        print("  No serial ports found. Is the board connected?")
    print("  0) Auto-detect (forget the saved port)")
    choice = input("Port number: ").strip()

    if choice in ("", "0"):
        if os.path.exists(LOCAL_INI):
            os.remove(LOCAL_INI)
        print("Saved port removed; PlatformIO will auto-detect the port.")
        return
    if not choice.isdigit() or not 1 <= int(choice) <= len(ports):
        print(f"Invalid choice: {choice}")
        env.Exit(1)

    device = ports[int(choice) - 1].device
    with open(LOCAL_INI, "w", encoding="utf-8", newline="\n") as f:
        f.write("; Generated by `pio run -t select_port`. Not committed.\n")
        f.write("[env]\n")
        f.write(f"upload_port = {device}\n")
        f.write(f"monitor_port = {device}\n")
    print(f"Saved {device} for upload and monitor in port.local.ini")


env.AddCustomTarget(
    name="select_port",
    dependencies=None,
    actions=[select_port],
    title="Select Port",
    description="Choose the serial port for upload and monitor",
    always_build=True,
)
